name: deep-signature
channels:
  - nvidia
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python
  - pytorch
  - torchaudio
  - torchvision
  - cudatoolkit=11.3
  - ipython
  - numpy
  - scipy
  - scikit-learn
  - scikit-image
  - jupyterlab
  - matplotlib
  - jupyter
  - pandas
  - cython
  - pytest
  - tqdm
  - opencv
  - freetype
  - plotly
  - ipykernel
  - pip
  - python-kaleido