name: deep-signature
channels:
  - conda-forge
  - nvidia
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - pytorch=1.12
  - torchaudio
  - torchvision
  - cudatoolkit=11.3
#  - ipython
  - numpy=1.22
  - scipy
  - scikit-learn
  - scikit-image
  - jupyterlab
  - matplotlib
#  - jupyter
  - pandas
#  - cython
#  - pytest
#  - tqdm
#  - opencv
#  - freetype=2.10.*
  - plotly
#  - ipykernel
#  - python-kaleido
  - numba
  - shapely
#  - numexpr
#  - bottleneck
#  - openpyxl
  - pip
#  - libwebp
  - pip:
#      - hausdorff
      - lightly
      - wandb
      - typed-argument-parser
      - gitpython
      - opencv-python
