name: deep-signature
channels:
  - nvidia
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - cudatoolkit=11.1
  - python
  - pytorch
  - torchaudio
  - torchvision
  - ipython
  - numpy
  - scipy
  - scikit-learn
  - scikit-image
  - cudatoolkit
  - jupyterlab
  - matplotlib
  - jupyter
  - pandas
  - cython
  - pytest
  - tqdm
  - opencv
  - freetype
  - pip
