name: deep-signature
channels:
  - conda-forge
  - nvidia
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchaudio
  - torchvision
  - cudatoolkit=11.3
  - ipython
  - numpy
  - scipy
  - scikit-learn
  - scikit-image
  - jupyterlab
  - matplotlib
  - jupyter
  - pandas
  - cython
  - pytest
  - tqdm
  - opencv
  - freetype=2.10.*
  - plotly
  - ipykernel
  - python-kaleido
  - numba
  - shapely
  - numexpr
  - bottleneck
  - openpyxl
  - pip
  - pip:
      - hausdorff
      - lightly
      - wandb
