name: deep-signature
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pytorch=1.3.0
  - torchvision=0.4.1
  - ipython
  - numpy
  - scipy
  - scikit-learn
  - cudatoolkit
  - jupyterlab
  - matplotlib
  - jupyter
  - pandas
  - cython
  - pytest
  - tqdm
  - opencv
  - freetype>=2.10
  - pip
