program: train_signature_euclidean_desktop
method: random
parameters:
    seed:
      value: 42
    results_base_dir_path:
      value: 'C:/deep-signature-data-new/training'
    training_curves_file_path:
      value: 'C:/deep-signature-data-new/curves/train/2022-12-20-02-02-52/curves.npy'
    validation_curves_file_path:
      value: 'C:/deep-signature-data-new/curves/validation/2022-12-20-09-02-36/curves.npy'
    test_curves_file_path:
      value: 'C:/deep-signature-data-new/curves/test/2022-12-30-23-10-33/curves.npy'
    group_name:
      value: 'euclidean'
    supporting_points_count:
      values: [3, 5, 7, 9]
    negative_examples_count:
      values: [2, 4]
    min_sampling_ratio:
      value: 0.3
    max_sampling_ratio:
      value: 0.9
    min_multimodality:
      value: 5
    max_multimodality:
      value: 15
    min_negative_example_offset:
      value: 20
    max_negative_example_offset:
      value: 100
    training_dataset_size:
      value: 1000
    validation_dataset_size:
      value: 1000
    training_items_buffer_size:
      value: 1000
    validation_items_buffer_size:
      value: 1000
    training_items_queue_maxsize:
      value: 2000
    validation_items_queue_maxsize:
      value: 2000
    training_num_workers:
      value: 3
    validation_num_workers:
      value: 3
    evaluation_num_workers:
      value: 2
    evaluation_benchmark_dir_path:
      value: "C:/deep-signature-data-new/curves/benchmark/2022-12-29-22-02-03"
    evaluation_curves_count_per_collection:
      value: 2
    evaluation_curve_collections_file_names:
      value: ["cats", "cacti"]
    evaluation_sampling_ratios:
      value: [0.6, 0.7, 0.8]
    evaluation_multimodality:
      value: 5
    epochs:
      value: 100
    training_batch_size:
      value: 1000
    validation_batch_size:
      value: 1000
    learning_rate:
      values: [0.1, 0.01, 0.001]
    checkpoint_rate:
      value: 10
    history_size:
      value: 800
    activation_fn:
      value: "sine"
    batch_norm_fn:
      value: "BatchNorm1d"
    in_features_size:
      values: [64, 128, 256]
    hidden_layer_repetitions:
      values: [1, 2, 3]
    training_min_det:
      value: 1
    training_max_det:
      value: 4
    training_min_cond:
      value: 1
    training_max_cond:
      value: 4
    validation_min_det:
      value: 2
    validation_max_det:
      value: 2
    validation_min_cond:
      value: 2
    validation_max_cond:
      value: 2