program: train_signature
method: random
parameters:
    seed:
      value: 42
    group_name:
      value: 'euclidean'
    supporting_points_count:
      values: [7]
    negative_examples_count:
      values: [2]
    min_sampling_ratio:
      value: 0.3
    max_sampling_ratio:
      value: 0.4
    min_multimodality:
      value: 5
    max_multimodality:
      value: 10
    min_negative_example_offset:
      value: 40
    max_negative_example_offset:
      value: 60
    training_dataset_size:
      value: 150000
    validation_dataset_size:
      value: 20000
    training_items_buffer_size:
      value: 150000
    validation_items_buffer_size:
      value: 20000
    training_items_queue_maxsize:
      value: 300000
    validation_items_queue_maxsize:
      value: 300000
    training_batch_size:
      value: 150000
    validation_batch_size:
      value: 20000
    evaluation_curves_count_per_collection:
      value: 6
    evaluation_curve_collections_file_names:
      value: ["wings", "whales", "trees"]
    evaluation_sampling_ratios:
      value: [0.7, 0.8, 0.9]
    evaluation_multimodality:
      value: 5
    epochs:
      value: 1000
    learning_rate:
      values: [0.01]
    checkpoint_rate:
      value: 100
    history_size:
      value: 800
    activation_fn:
      value: "sine"
    batch_norm_fn:
      value: "BatchNorm1d"
    in_features_size:
      values: [64]
    hidden_layer_repetitions:
      values: [2]
    training_min_det:
      value: 1
    training_max_det:
      value: 4
    training_min_cond:
      value: 1
    training_max_cond:
      value: 4
    validation_min_det:
      value: 2
    validation_max_det:
      value: 2
    validation_min_cond:
      value: 2
    validation_max_cond:
      value: 2