program: train_signature_euclidean_desktop
method: random
parameters:
    training_curves_file_path: "C:/deep-signature-data-new/curves/train/2022-12-20-02-02-52"
    validation_curves_file_path: "C:/deep-signature-data-new/curves/validation/2022-12-20-09-02-36"
    group_name:
      value: 'euclidean'
    supporting_points_count:
      values: [3, 5, 7, 9]
    negative_examples_count:
      values: [2, 4]
    min_sampling_ratio:
      value: 0.3
    max_sampling_ratio:
      value: 0.9
    min_multimodality:
      value: 5
    max_multimodality:
      value: 15
    min_negative_example_offset:
      value: 20
    max_negative_example_offset:
      value: 100
    training_dataset_size:
      value: 100000
    validation_dataset_size:
      value: 20000
    training_num_workers:
      value: 10
    validation_num_workers:
      value: 2
    evaluation_num_workers:
      value: 2
    evaluation_benchmark_dir_path:
      value: "C:/deep-signature-data-new/curves/benchmark/2022-12-16-01-11-24"
    evaluation_curves_count_per_collection:
      value: 30
    evaluation_curve_collections_file_names:
      value: ["cats, cacti"]
    evaluation_sampling_ratios:
      value [0.6, 0.7, 0.8, 0.9]
    evaluation_multimodality:
      value: 5
    epochs:
      value: 100
    batch_size:
      value: 20000
    learning_rate:
      values: [0.1, 0.01, 0.001]
    checkpoint_rate:
      value: 10
    history_size:
      value: 800
    activation_fn:
      value: "sine"
    batch_norm_fn:
      value: "BatchNorm1d"
    in_features_size:
      values: [64, 128, 256]
    hidden_layer_repetitions:
      values: [1, 2, 3]

