program: train_signature_euclidean_desktop
method: random
parameters:
    seed:
      value: 42
    group_name:
      value: 'euclidean'
    supporting_points_count:
      values: [3, 5, 7, 9]
    negative_examples_count:
      values: [2, 4]
    min_sampling_ratio:
      value: 0.3
    max_sampling_ratio:
      value: 0.9
    min_multimodality:
      value: 5
    max_multimodality:
      value: 15
    min_negative_example_offset:
      value: 20
    max_negative_example_offset:
      value: 100
    training_dataset_size:
      value: 100000
    validation_dataset_size:
      value: 20000
    training_items_buffer_size:
      value: 100000
    validation_items_buffer_size:
      value: 20000
    training_items_queue_maxsize:
      value: 200000
    validation_items_queue_maxsize:
      value: 200000
    training_batch_size:
      value: 100000
    validation_batch_size:
      value: 20000
    evaluation_curves_count_per_collection:
      value: 10
    evaluation_curve_collections_file_names:
      value: ["wings", "whales", "trees", "spiders", "signs", "shields", "shapes"]
    evaluation_sampling_ratios:
      value: [0.7, 0.8, 0.9]
    evaluation_multimodality:
      value: 5
    epochs:
      value: 200
    learning_rate:
      values: [0.01, 0.001, 0.0001]
    checkpoint_rate:
      value: 10
    history_size:
      value: 800
    activation_fn:
      value: "sine"
    batch_norm_fn:
      value: "BatchNorm1d"
    in_features_size:
      values: [64, 128, 256]
    hidden_layer_repetitions:
      values: [1, 2, 3]
    training_min_det:
      value: 1
    training_max_det:
      value: 4
    training_min_cond:
      value: 1
    training_max_cond:
      value: 4
    validation_min_det:
      value: 2
    validation_max_det:
      value: 2
    validation_min_cond:
      value: 2
    validation_max_cond:
      value: 2