circles_dir_path_train = "C:/deep-signature-data/circles/curves/train"
circles_dir_path_test = "C:/deep-signature-data/circles/curves/test"
circles_section_tuplets_dir_path = "C:/deep-signature-data/circles/datasets/tuplets/sections"
circles_triangle_tuplets_dir_path = "C:/deep-signature-data/circles/datasets/tuplets/triangles"
circles_section_tuplets_results_dir_path = "C:/deep-signature-data/circles/results/tuplets/sections"
circles_triangle_tuplets_results_dir_path = "C:/deep-signature-data/circles/results/tuplets/triangles"